# Generated by Django 3.2.16 on 2026-02-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_telebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='flight_type',
            field=models.CharField(choices=[('free', 'Свободные полеты'), ('motor', 'Моторные полеты')], default='free', max_length=10, verbose_name='Тип полетов'),
        ),
    ]
